name: Deploy to Staging

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Deploy to Railway Staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Railway Configuration
        run: |
          if [ -z "${{ secrets.RAILWAY_TOKEN }}" ]; then
            echo "❌ RAILWAY_TOKEN secret is not configured"
            echo "Please add the following secrets to your GitHub repository:"
            echo "1. RAILWAY_TOKEN - Your Railway API token"
            echo "2. RAILWAY_SERVICE_ID - Your Railway service ID"
            echo "3. STAGING_URL - Your staging environment URL"
            echo ""
            echo "To get your Railway token, run: railway auth"
            echo "To get your service ID, run: railway status"
            exit 1
          fi
          echo "✅ Railway secrets are configured"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: betmate-api/package-lock.json

      - name: Install dependencies
        working-directory: ./betmate-api
        run: npm ci

      - name: Build application
        working-directory: ./betmate-api
        run: npm run build

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Verify Railway Authentication
        run: |
          echo "Verifying Railway authentication..."
          railway whoami || (echo "❌ Railway authentication failed" && exit 1)
          echo "✅ Railway authentication successful"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway Staging
        working-directory: ./betmate-api
        run: |
          echo "🚀 Deploying to Railway staging environment..."
          if [ -n "${{ secrets.RAILWAY_SERVICE_ID }}" ]; then
            railway deploy --service ${{ secrets.RAILWAY_SERVICE_ID }} --environment staging
          else
            echo "⚠️ No service ID specified, deploying to linked service..."
            railway deploy --environment staging
          fi
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Run post-deployment health check
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30
          curl -f ${{ secrets.STAGING_URL }}/health || exit 1
          echo "Staging deployment successful!"

  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Notify Success
        if: needs.deploy.result == 'success'
        run: echo "✅ Staging deployment successful!"

      - name: Notify Failure
        if: needs.deploy.result == 'failure'
        run: echo "❌ Staging deployment failed!"