name: Deploy to Staging

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Deploy to Railway Staging
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: betmate-api/package-lock.json

      - name: Install dependencies
        working-directory: ./betmate-api
        run: npm ci

      - name: Build application
        working-directory: ./betmate-api
        run: npm run build

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway Staging
        working-directory: ./betmate-api
        run: railway deploy --service ${{ secrets.RAILWAY_SERVICE_ID }} --environment staging
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Run post-deployment health check
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30
          curl -f ${{ secrets.STAGING_URL }}/health || exit 1
          echo "Staging deployment successful!"

  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Notify Success
        if: needs.deploy.result == 'success'
        run: echo "✅ Staging deployment successful!"

      - name: Notify Failure
        if: needs.deploy.result == 'failure'
        run: echo "❌ Staging deployment failed!"